/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.salesdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;





/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name="CUSTOMERS"
    ,schema="PUBLIC"
    ,catalog="PUBLIC"
)
public class Customers  implements java.io.Serializable {


     private Integer id;
     private States states;
     private String name;
     private Set<Leads> leadses = new HashSet<Leads>(0);

    public Customers() {
    }

	
    public Customers(String name) {
        this.name = name;
    }
    public Customers(States states, String name, Set<Leads> leadses) {
       this.states = states;
       this.name = name;
       this.leadses = leadses;
    }

     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="STATE_ID")
    public States getStates() {
        return this.states;
    }
    
    public void setStates(States states) {
        this.states = states;
    }

    
    @Column(name="NAME", nullable=false, length=32)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="customers")
    public Set<Leads> getLeadses() {
        return this.leadses;
    }
    
    public void setLeadses(Set<Leads> leadses) {
        this.leadses = leadses;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof Customers) )
		 return false;

		 Customers that = ( Customers ) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
     }


}

