/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.salesdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;





/**
 * FollowUps generated by hbm2java
 */
@Entity
@Table(name="FOLLOW_UPS"
    ,schema="PUBLIC"
    ,catalog="PUBLIC"
)
public class FollowUps  implements java.io.Serializable {


     private Integer id;
     private Quotes quotes;
     private Date entryDate;

    public FollowUps() {
    }

	
    public FollowUps(Date entryDate) {
        this.entryDate = entryDate;
    }
    public FollowUps(Quotes quotes, Date entryDate) {
       this.quotes = quotes;
       this.entryDate = entryDate;
    }

     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="QUOTE_ID")
    public Quotes getQuotes() {
        return this.quotes;
    }
    
    public void setQuotes(Quotes quotes) {
        this.quotes = quotes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE", nullable=false, length=10)
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }



public boolean equals(Object o) {
         if (this == o)
         return true;
		 if ( (o == null ) )
		 return false;
		 if ( !(o instanceof FollowUps) )
		 return false;

		 FollowUps that = ( FollowUps ) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );

   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
     }


}

