/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.salesvision2_0.myjavaservice1.controller;

import com.salesvision2_0.myjavaservice1.MyJavaService1;
import java.lang.String;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.*;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/myJavaService1")
public class MyJavaService1Controller {

    @Autowired
    private MyJavaService1 myJavaService1;

    @RequestMapping(value = "/sampleJavaOperation", produces = MediaType.APPLICATION_JSON_VALUE, method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public String sampleJavaOperation() {
        return myJavaService1.sampleJavaOperation();
    }
}
