/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.salesdb.*;


/**
 * ServiceImpl object for domain model class Sales.
 * @see com.salesdb.Sales
 */
@Service("salesdb.SalesService")
public class SalesServiceImpl implements SalesService {


    private static final Logger LOGGER = LoggerFactory.getLogger(SalesServiceImpl.class);

    @Autowired
    @Qualifier("salesdb.SalesDao")
    private WMGenericDao<Sales, Integer> wmGenericDao;
    public void setWMGenericDao(WMGenericDao<Sales, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "salesdbTransactionManager")
     public Page<Sales> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "salesdbTransactionManager")
    @Override
    public Sales create(Sales sales) {
        LOGGER.debug("Creating a new sales with information: {}" , sales);
        return this.wmGenericDao.create(sales);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "salesdbTransactionManager")
    @Override
    public Sales delete(Integer salesId) throws EntityNotFoundException {
        LOGGER.debug("Deleting sales with id: {}" , salesId);
        Sales deleted = this.wmGenericDao.findById(salesId);
        if (deleted == null) {
            LOGGER.debug("No sales found with id: {}" , salesId);
            throw new EntityNotFoundException(String.valueOf(salesId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Page<Sales> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all saless");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Page<Sales> findAll(Pageable pageable) {
        LOGGER.debug("Finding all saless");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Sales findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding sales by id: {}" , id);
        Sales sales=this.wmGenericDao.findById(id);
        if(sales==null){
            LOGGER.debug("No sales found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return sales;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "salesdbTransactionManager")
    @Override
    public Sales update(Sales updated) throws EntityNotFoundException {
        LOGGER.debug("Updating sales with information: {}" , updated);
        this.wmGenericDao.update(updated);
        return this.wmGenericDao.findById((Integer)updated.getId());
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


