/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.salesdb.*;

/**
 * Service object for domain model class Sales.
 * @see com.salesdb.Sales
 */

public interface SalesService {
   /**
	 * Creates a new sales.
	 * 
	 * @param created
	 *            The information of the created sales.
	 * @return The created sales.
	 */
	public Sales create(Sales created);

	/**
	 * Deletes a sales.
	 * 
	 * @param salesId
	 *            The id of the deleted sales.
	 * @return The deleted sales.
	 * @throws EntityNotFoundException
	 *             if no sales is found with the given id.
	 */
	public Sales delete(Integer salesId) throws EntityNotFoundException;

	/**
	 * Finds all saless.
	 * 
	 * @return A list of saless.
	 */
	public Page<Sales> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Sales> findAll(Pageable pageable);
	
	/**
	 * Finds sales by id.
	 * 
	 * @param id
	 *            The id of the wanted sales.
	 * @return The found sales. If no sales is found, this method returns
	 *         null.
	 */
	public Sales findById(Integer id) throws EntityNotFoundException;
	/**
	 * Updates the information of a sales.
	 * 
	 * @param updated
	 *            The information of the updated sales.
	 * @return The updated sales.
	 * @throws EntityNotFoundException
	 *             if no sales is found with given id.
	 */
	public Sales update(Sales updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the saless in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the sales.
	 */

	public long countAll();


    public Page<Sales> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

