/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/


package com.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

public interface SalesdbQueryExecutorService {
    Page<Object> executeWeeklySales(Pageable pageable, java.lang.Integer year, java.lang.Integer month) throws QueryParameterMismatchException;
    Page<Object> executeWeeklyQuotes(Pageable pageable, java.lang.Integer year, java.lang.Integer month) throws QueryParameterMismatchException;
    Page<Object> executeWeeklyLeads(Pageable pageable, java.lang.Integer year, java.lang.Integer month) throws QueryParameterMismatchException;
    Page<Object> executeWeeklyFollowUps(Pageable pageable, java.lang.Integer year, java.lang.Integer month) throws QueryParameterMismatchException;
    Page<Object> executeLeadsCount(Pageable pageable, java.lang.Integer channel) throws QueryParameterMismatchException;
    Page<Object> executeRepsCount(Pageable pageable, java.lang.Integer channel) throws QueryParameterMismatchException;
    Page<Object> executeSalesRevenueAndCount(Pageable pageable, java.lang.Integer channel) throws QueryParameterMismatchException;
    Page<Object> executeTopTrendingProducts(Pageable pageable, java.lang.Integer year, java.lang.Integer month) throws QueryParameterMismatchException;
    Page<Object> executeSalesByReps(Pageable pageable, java.lang.Integer channel) throws QueryParameterMismatchException;
    Page<Object> executeSalesByChannels(Pageable pageable, java.lang.Integer year, java.lang.Integer month) throws QueryParameterMismatchException;
    Page<Object> executeWeeklyConverted(Pageable pageable, java.lang.Integer year, java.lang.Integer month) throws QueryParameterMismatchException;
    Page<Object> executeRevenueHeatMap(Pageable pageable, java.lang.Integer year, java.lang.Integer month) throws QueryParameterMismatchException;
    Page<Object> executeCustomersRatio(Pageable pageable, java.lang.Integer year, java.lang.Integer month) throws QueryParameterMismatchException;
    Page<Object> executeLeadsByChannel(Pageable pageable, java.lang.Integer channel) throws QueryParameterMismatchException;
    Page<Object> executeSalesByEachRep(Pageable pageable, java.lang.Integer id) throws QueryParameterMismatchException;
    Page<Object> executeEachRepCustomerWiseSales(Pageable pageable, java.lang.Integer id) throws QueryParameterMismatchException;

	
	Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) ;

	int executeWMCustomQueryUpdate(CustomQuery query) ;
}

