/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.salesdb.*;

/**
 * Service object for domain model class States.
 * @see com.salesdb.States
 */

public interface StatesService {
   /**
	 * Creates a new states.
	 * 
	 * @param created
	 *            The information of the created states.
	 * @return The created states.
	 */
	public States create(States created);

	/**
	 * Deletes a states.
	 * 
	 * @param statesId
	 *            The id of the deleted states.
	 * @return The deleted states.
	 * @throws EntityNotFoundException
	 *             if no states is found with the given id.
	 */
	public States delete(Integer statesId) throws EntityNotFoundException;

	/**
	 * Finds all statess.
	 * 
	 * @return A list of statess.
	 */
	public Page<States> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<States> findAll(Pageable pageable);
	
	/**
	 * Finds states by id.
	 * 
	 * @param id
	 *            The id of the wanted states.
	 * @return The found states. If no states is found, this method returns
	 *         null.
	 */
	public States findById(Integer id) throws EntityNotFoundException;
	/**
	 * Updates the information of a states.
	 * 
	 * @param updated
	 *            The information of the updated states.
	 * @return The updated states.
	 * @throws EntityNotFoundException
	 *             if no states is found with given id.
	 */
	public States update(States updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the statess in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the states.
	 */

	public long countAll();


    public Page<States> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

