/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.salesdb.*;


/**
 * ServiceImpl object for domain model class Tasks.
 * @see com.salesdb.Tasks
 */
@Service("salesdb.TasksService")
public class TasksServiceImpl implements TasksService {


    private static final Logger LOGGER = LoggerFactory.getLogger(TasksServiceImpl.class);

    @Autowired
    @Qualifier("salesdb.TasksDao")
    private WMGenericDao<Tasks, Integer> wmGenericDao;
    public void setWMGenericDao(WMGenericDao<Tasks, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "salesdbTransactionManager")
     public Page<Tasks> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "salesdbTransactionManager")
    @Override
    public Tasks create(Tasks tasks) {
        LOGGER.debug("Creating a new tasks with information: {}" , tasks);
        return this.wmGenericDao.create(tasks);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "salesdbTransactionManager")
    @Override
    public Tasks delete(Integer tasksId) throws EntityNotFoundException {
        LOGGER.debug("Deleting tasks with id: {}" , tasksId);
        Tasks deleted = this.wmGenericDao.findById(tasksId);
        if (deleted == null) {
            LOGGER.debug("No tasks found with id: {}" , tasksId);
            throw new EntityNotFoundException(String.valueOf(tasksId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Page<Tasks> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all taskss");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Page<Tasks> findAll(Pageable pageable) {
        LOGGER.debug("Finding all taskss");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Tasks findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding tasks by id: {}" , id);
        Tasks tasks=this.wmGenericDao.findById(id);
        if(tasks==null){
            LOGGER.debug("No tasks found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return tasks;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "salesdbTransactionManager")
    @Override
    public Tasks update(Tasks updated) throws EntityNotFoundException {
        LOGGER.debug("Updating tasks with information: {}" , updated);
        this.wmGenericDao.update(updated);
        return this.wmGenericDao.findById((Integer)updated.getId());
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


